language: python

python:
  - 2.7
  - 3.4
  - 3.3
  - 3.5
  - 3.6

sudo: required
services: [docker]

install: pip install -r requirements.txt
script:
  - nosetests -v tests --with-coverage --cover-erase --cover-package docktors

jobs:
  include:
    - stage: Integration Test
      only: [master, developpment]
      install:
        - sudo service mysql stop
        - pip install -r requirements.txt
        - for img in alpine mysql; do docker pull "$img"; done
      script:
        - nosetests -v it.tests tests --with-coverage --cover-erase --cover-package docktors
        - pycodestyle --config .pycodestyle docktors it.tests tests
        - flake8 --config .pycodestyle docktors it.tests tests
        - pylint --rcfile .pylintrc *.py docktors
      after_success:
        - codecov
        - version=$(cat VERSION) && echo "$version.dev${TRAVIS_JOB_NUMBER%.*}" | tee VERSION
      deploy:
        provider: pypi
        server: https://testpypi.python.org/pypi
        user: Patouche
        password: $PYPI_PASSWORD
        skip_upload_docs: true
        skip_cleanup: true
        on:
          all_branches: true
    - stage: Deploy in PyPi
      only: [master]
      script:
        - echo "$TRAVIS_TAG" | sed 's/^v//gi' | tee VERSION
      deploy:
        provider: pypi
        user: Patouche
        password: $PYPI_PASSWORD
        skip_upload_docs: true
        skip_cleanup: true
        on:
          tags: true
