language: python

python:
  - 2.7
  - 3.4
  - 3.3
  - 3.5
  - 3.6

sudo: required
services: [docker]

install: pip install -r requirements.txt
script: nosetests -v tests --with-coverage --cover-erase --cover-package docktors

jobs:
  include:
    - stage: Integration Test
      branches:
        only: [master, developpment]
      script: .ci/integ-tests.sh
    - stage: Github Release
      branches:
        only: [master]
      install: skip
      script: if [[ "$TRAVIS_BRANCH" == "master" ]]; then .ci/release.sh; fi
    - stage: Deploy in PyPi
      branches:
        only: [master, developpment]
      script:
        - export LIB_VERSION=$(cat VERSION)
        - if [[ "$TRAVIS_BRANCH" == "master" ]]; then export PYPI_SERVER=upload; fi
        - if [[ "$TRAVIS_BRANCH" == "developpment" ]]; then export PYPI_SERVER=test; fi
        - if [[ "$TRAVIS_BRANCH" != "master" ]]; then echo "${LIB_VERSION}.dev${TRAVIS_JOB_NUMBER%.*}" > VERSION; fi
      deploy:
        provider: pypi
        server: https://${PYPI_SERVER}.pypi.org/legacy/
        user: Patouche
        password: $PYPI_PASSWORD
        skip_upload_docs: true
        skip_cleanup: true
        on:
          all_branches: true
          condition: "! -z $PYPI_SERVER"
