language: python

python:
  - 2.7
  - 3.4
  - 3.3
  - 3.5
  - 3.6

sudo: required
services: [docker]

install: pip install -r requirements.txt
script:
  - nosetests -v tests --with-coverage --cover-erase --cover-package docktors

jobs:
  include:
    - stage: Integration Test
      only: [master, developpment]
      install:
        - sudo service mysql stop
        - pip install -r requirements.txt
        - for img in alpine mysql; do docker pull "$img"; done
      script:
        - nosetests -v it.tests tests --with-coverage --cover-erase --cover-package docktors
        - pycodestyle --config .pycodestyle docktors it.tests tests
        - flake8 --config .pycodestyle docktors it.tests tests
      after_success:
        - codecov
      deploy:
        provider: pypi
        server: https://testpypi.python.org/pypi
        user: Patouche
        password: $PYPI_PASSWORD
        on:
          branch: developpment
    - stage: Deploy in PyPi
      script:
        - git describe --tags --abbrev=0 | sed 's/^v//gi' | tee VERSION
      deploy:
        provider: pypi
        user: Patouche
        password: $PYPI_PASSWORD
      on:
        tags: true
