language: python

python:
  - 2.7
  - 3.4
  - 3.3
  - 3.5
  - 3.6

sudo: required
services: [docker]

install: pip install -r requirements.txt
script: nosetests -v tests --with-coverage --cover-erase --cover-package docktors

jobs:
  include:
    - stage: Integration Test
      only: [master, developpment]
      script: .ci/integ-tests.sh
    - stage: Deploy in PyPi
      only: [master, developpment]
      env:
      script:
        - export PYPI_SERVER=testpypi
        - test $TRAVIS_BRANCH != 'master' && v=$(cat VERSION) && echo "${v}.dev${TRAVIS_JOB_NUMBER%.*}" > VERSION || true
        - test $TRAVIS_BRANCH = 'master' && export PYPI_SERVER=pypi || true
        - test $TRAVIS_BRANCH = 'master' && .ci/release.sh || true
      deploy:
        provider: pypi
        server: https://${PYPI_SERVER}.python.org/pypi
        user: Patouche
        password: $PYPI_PASSWORD
        skip_upload_docs: true
        skip_cleanup: true
        on:
          all_branches: true
